### ISSUE TITLE
Animation properties incorrectly defined

### ISSUE THREAD

**Issue by MellowArpeggiation** [scottcanoni/react-anagram-animation#4]
The animation CSS property shorthand is incorrectly defined, with commas between all the animation property values. This is parsed by the browser as multiple different animation properties, and means that the rules are applied in unexpected ways (in this case, the 2s delay and ease-in-out is dropped, but the animation still occurs over 2s which seems intended and looks good).

`transition: all, 2s, ease-in-out, 2s;` is interpreted by the browser as

```
transition-delay 0s, 0s, 0s, 0s;
transition-duration 0s, 2s, 0s, 2s;
transition-property all, all, all, all;
transition-timing-function ease, ease, ease-in-out, ease;
```

I'm gonna fork and fix the issue (or more likely, move the transition property into the component handler so we can define a custom timing function! I have a few other ideas I want to try out so we'll see how we go)

**Comment by scottcanoni** [comment]
Fixed perfectly, thank you!
