### ISSUE TITLE
Doesn't work on React 18

### ISSUE THREAD

**Issue by wzard** [scottcanoni/react-anagram-animation#6]
Codesandbox: https://codesandbox.io/s/relaxed-panna-ypxhn7?file=/src/App.js

Can you upgrade the library to use with React 18?

**Comment by scottcanoni** [comment]
I updated the dependencies to React 18 and created this beta version of my library:
https://github.com/scottcanoni/react-anagram-animation/tree/react18

I confirmed it works as expected:
![image](https://user-images.githubusercontent.com/2506805/176922832-9f90f987-e17b-4b90-a3ad-053ba5420701.png)

It's not loading correctly on codesandbox.io but if you need that, I will leave that to you or someone else to investigate.  Also, I don't see a way to support both React 17 and 18 with the same version.  Until React 18 is more widely used, this will remain as a beta version.

Please check and provide any possible feedback.  Contributions are welcome, so if you want to improve something, please open a merge request.  Cheers!

**Comment by scottcanoni** [comment]
I updated this React 18 specific branch once more with some dependency updates.  If you know of a way to support both React 17 and 18 at the same time, please let me know.  Otherwise, you can use this branch: https://github.com/scottcanoni/react-anagram-animation/tree/react18
