### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by zinTD** [scottcanoni/react-anagram-animation#7]
I followed all steps from codesandbox and it is not working. Can you answer me ? It shows the first word in words array and that's it.

**Comment by scottcanoni** [comment]
Which version of react are you using?

This version uses React 17: https://codesandbox.io/s/pcszv?file=/src/App.js

**Comment by scottcanoni** [comment]
Try using version "react-anagram-animation": "1.2.0" with react 17.  Re-open if you have issue.

**Comment by scottcanoni** [comment]
@zinTD , this shows the latest version `1.3.1`, which was published today, working with React 17:

https://codesandbox.io/s/react-anagram-animation-forked-hpg7lz?file=/package.json

**Comment by zinTD** [comment]
Hi, I saw your  Bugfix for React 18
<https://github.com/scottcanoni/react-anagram-animation/commit/42333c2e8bdde1e40d083c7e3505d87fed7a2203>
 .
And I have upgraded react-anagram-animation to 1.3.1
However, still , not working.

**Comment by zinTD** [comment]
my react version  18.2.0
React-anagram-animation 1.3.1

**Comment by scottcanoni** [comment]
Hi @zinTD , there is an issue with a dependency `use-font-face-observer` which throws an error on code sandbox: https://uqb1oi.csb.app/

Now, in a local project, I am using React 18 and the animation loads just fine.  I am trying to support both React 17 and 18 at the same time and that does not seem possible.  I may have to revert back to react 17.  Are you able to use react 17?  If so, please try version 1.2.0 of react-anagram-animation

**Comment by zinTD** [comment]
Thank you.
You did it awesome.
